#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════════════
#  TIMELINE HEADER — the chronology written INTO the note, not printed at it.
#  (Jake, 2026-08-17)
#
#  HIS SPEC, VERBATIM:
#    "I don't care about the output. I'll never go in there and read it. I want it
#     archived in a manner in which you're date stamping, and filing into a folder …
#     so that when a new 'Iran' piece is uploaded, when you go into the vault 'Iran'
#     is the keyword and the gate you enter brings you from the start. Or maybe each
#     file gets a written summary on top. Because if I load something that is load
#     bearing from something in March, I want [Claude] to immediately recognize the
#     indication because it just read that entire timeline before ingesting."
#
#  ⇒ THE DISTINCTION THAT MATTERS: `thread_arc.py` COMPUTES a timeline when a tool is
#  run. This WRITES it to disk, dated and committed, so it is simply THERE when the
#  note is opened — no tool call, no remembering. A printout is not an archive.
#
#  WHAT IT WRITES, between sentinels, directly under each note's H1:
#    • span (first → last dated entry), entry count, last refresh
#    • the SPINE: every dated entry, ascending, one line, with its LINE NUMBER
#  Regenerating is idempotent: the block is replaced, never appended.
#
#  ⚠️ THE SENTINELS ARE LOAD-BEARING. librarian.py (magnitude collision / anchor) and
#  thread_arc.py both SKIP the block — otherwise every figure quoted in a spine line
#  would double-count as a fresh vault statement and the collision check would start
#  matching itself.
#
#  USAGE
#    python3 tools/timeline_header.py --all            # refresh every note
#    python3 tools/timeline_header.py --note wiki/rates-board.md
#    python3 tools/timeline_header.py --check          # which notes are stale
#    python3 tools/timeline_header.py --threads        # rebuild wiki/_timelines/*.md
# ═══════════════════════════════════════════════════════════════════════════
import os, re, sys, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(ROOT, 'wiki')
TLDIR = os.path.join(WIKI, '_timelines')
sys.path.insert(0, os.path.join(ROOT, 'tools'))

BEGIN = '<!-- TIMELINE:BEGIN — auto-generated by tools/timeline_header.py · do not hand-edit -->'
END = '<!-- TIMELINE:END -->'
DATE = re.compile(r'(20\d\d-\d\d-\d\d)')


def clock():
    return subprocess.run(['date', '+%Y-%m-%d %H:%M %Z'],
                          env={**os.environ, 'TZ': 'America/Los_Angeles'},
                          capture_output=True, text=True).stdout.strip()


def strip_block(text):
    """Remove an existing timeline block. Idempotence is the whole contract here —
    a header that appends instead of replacing would grow without bound."""
    if BEGIN not in text:
        return text
    pre, rest = text.split(BEGIN, 1)
    if END in rest:
        rest = rest.split(END, 1)[1]
        return (pre.rstrip('\n') + '\n' + rest.lstrip('\n'))
    return text


def notes():
    out = []
    for dp, dns, fns in os.walk(WIKI):
        dns[:] = [d for d in dns if d != '_timelines']
        out += [os.path.join(dp, f) for f in fns if f.endswith('.md')]
    return sorted(out)


def spine(text):
    """Every dated entry header, ascending. Line numbers are computed AFTER the block is
    stripped, then offset when it is re-inserted, so the refs point at the real entries."""
    rows = []
    for i, ln in enumerate(text.split('\n'), 1):
        # TWO ENTRY SHAPES. Long argument notes date their '#' headers; BOARD-style notes
        # (rates-board, balance-sheet-board) carry '- [YYYY-MM-DD]' bullets instead and
        # have no dated headers at all — the first build gave rates-board '0 entries'.
        if ln.startswith('#'):
            m = DATE.search(ln)
            if not m:
                continue
            txt = re.sub(r'^#+\s*', '', ln).strip()
        elif re.match(r'\s{0,2}[-*] +\*{0,2}\[20\d\d-\d\d-\d\d\]', ln):
            m = DATE.search(ln)
            txt = re.sub(r'^\s*[-*] +', '', ln).strip()
        else:
            continue
        txt = re.sub(r'\s+', ' ', txt)
        rows.append((m.group(1), i, txt))
    rows.sort(key=lambda r: (r[0], r[1]))
    return rows


def render_block(rows, offset, width=118):
    if not rows:
        body = ['_(no dated entries yet)_']
        span = 'empty'
    else:
        span = f'{rows[0][0]} → {rows[-1][0]}'
        body, cur = [], None
        for d, i, txt in rows:
            if d[:7] != cur:
                cur = d[:7]
                body.append(f'**{cur}**')
            body.append(f'- `{d}` `L{i + offset}` {txt[:width]}')
    head = [
        BEGIN,
        '> ## ⏱ TIMELINE — read this BEFORE the entry you came for.',
        f'> **{len(rows)} dated entries · {span} · refreshed {clock()}**',
        '>',
        '> This is the note **from the start, in order**. A new inbound is the NEXT TICK of',
        '> this sequence — read the arc first, then the entry. A March line can be the',
        '> load-bearing one; nothing here is ranked by recency.',
        '',
    ]
    return '\n'.join(head + body + ['', END, ''])


def apply(path, write=True):
    raw = open(path, errors='replace').read()
    base = strip_block(raw)
    lines = base.split('\n')
    # insert directly after the H1 (or at top if there is none)
    at = 0
    for i, ln in enumerate(lines):
        if ln.startswith('# '):
            at = i + 1
            break
    rows = spine(base)
    # ⛔ THE BLOCK SHIFTS THE LINES IT POINTS AT. First version guessed the height from
    # newline counts and every ref landed on a blank line. MEASURE the rendered prefix
    # instead of predicting it, and iterate until the offset stops moving.
    offset, out = 0, None
    for _ in range(6):
        blk = render_block(rows, offset)
        prefix = '\n'.join(lines[:at] + ['', blk])
        added = len(prefix.split('\n')) - at
        if added == offset:
            break
        offset = added
    blk = render_block(rows, offset)
    out = '\n'.join(lines[:at] + ['', blk] + lines[at:])
    # ⛔ IDEMPOTENCE: the refresh stamp changes on every run, so a naive compare rewrote
    # all 68 notes every time — pure git churn that would bury real diffs. Compare the
    # SPINE only; if it is unchanged, keep the old stamp and touch nothing.
    def despan(t):
        return re.sub(r'\*\*\d+ dated entries · .*? · refreshed [^*]*\*\*', '', t)
    if despan(out) == despan(raw):
        return False, len(rows)
    if write:
        open(path, 'w').write(out)
    return True, len(rows)


def build_threads():
    """The KEYWORD GATE: one merged chronology per thread, so 'Iran' resolves to a single
    file that starts at the beginning — rather than three notes the reader must interleave."""
    try:
        from vault_router import ROUTE
        import thread_arc as TA
    except Exception as e:
        print(f'  (cannot build thread timelines: {e})'); return 0
    os.makedirs(TLDIR, exist_ok=True)
    n = 0
    for th in sorted(ROUTE):
        paths = TA.notes_for_thread(th)
        if not paths:
            continue
        rows = []
        for p in paths:
            base = strip_block(open(p, errors='replace').read())
            rel = os.path.relpath(p, ROOT)
            for d, i, txt in spine(base):
                rows.append((d, rel, i, txt))
        if not rows:
            continue
        rows.sort(key=lambda r: (r[0], r[1], r[2]))
        slug = re.sub(r'[^a-z0-9]+', '-', th.lower()).strip('-')   # 'BLACK SEA' -> black-sea (was writing 'black sea.md')
        body = [f'# ⏱ {th} — merged timeline (the gate)', '',
                f'> **{len(rows)} dated entries across {len(paths)} notes · '
                f'{rows[0][0]} → {rows[-1][0]} · refreshed {clock()}**',
                '>', '> **This file is the ENTRY POINT for this thread.** It is the whole thread in order,',
                '> oldest first, across every note that carries it. Read it start-to-finish before',
                '> responding to an inbound on this thread — that is what makes a March line land.',
                '>', '> Auto-generated by `tools/timeline_header.py --threads`. Do not hand-edit.', '',
                '**Notes merged:** ' + ' · '.join(f'`{os.path.relpath(p, ROOT)}`' for p in paths), '']
        cur = None
        for d, rel, i, txt in rows:
            if d[:7] != cur:
                cur = d[:7]
                body += ['', f'## {cur}', '']
            body.append(f'- `{d}` [{os.path.basename(rel)}:L{i}]({os.path.relpath(os.path.join(ROOT, rel), TLDIR)}) — {txt[:150]}')
        open(os.path.join(TLDIR, f'{slug}.md'), 'w').write('\n'.join(body) + '\n')
        n += 1
    return n



# ── THE CHAIN (Jake, 2026-08-18): a CAUSAL ORDER, stage 1 prices stage 2, and so on.
# Kept here rather than in the router because it is an ORDERING, not a keyword match.
CHAIN = [
    ('1', 'TREASURIES',        ['rates-board.md', 'new-economy-regime.md']),
    ('2', 'HYPERSCALER CREDIT',['hyperscaler-credit.md']),
    ('3', 'FUNDING APPETITE',  ['ai-financing-fragility.md', 'balance-sheet-board.md']),
    ('4', 'CAPEX COMMITMENTS', ['ai-capex-cycle.md', 'cepi.md']),
    ('5', 'SUPPLIER ORDERS',   ['metered-compute.md', 'memory-regime-question.md', 'compression-thesis.md']),
]


def build_chain():
    """The MERGED CHAIN LOG: all five stages in ONE chronology, each line tagged with its stage.
    ⇒ This is what makes the causal hypothesis testable — if stage N really leads stage N+1, it
    has to show up as stage-N lines clustering BEFORE stage-N+1 lines around each turn."""
    os.makedirs(TLDIR, exist_ok=True)
    rows, present = [], []
    for num, name, files in CHAIN:
        got = []
        for fn in files:
            for dp, _, fns in os.walk(WIKI):
                if fn in fns:
                    p = os.path.join(dp, fn)
                    got.append(os.path.relpath(p, ROOT))
                    base = strip_block(open(p, errors='replace').read())
                    for d, i, txt in spine(base):
                        rows.append((d, num, name, os.path.basename(fn), i, txt))
        present.append((num, name, got))
    if not rows:
        return 0
    rows.sort(key=lambda r: (r[0], r[1]))
    out = ['# ⏱ THE TRANSMISSION CHAIN — merged running log, all five stages, oldest first', '',
           f'> **{len(rows)} dated entries · {rows[0][0]} → {rows[-1][0]} · refreshed {clock()}**', '>',
           '> **Treasuries → hyperscaler CDS/spreads → funding appetite → capex commitments → supplier',
           '> orders.** Each line is tagged with its STAGE. Read top-to-bottom: this is the whole chain',
           '> as one history, which is the only way to see whether a shock at stage 1 actually',
           '> propagated — or died on the way down. See `wiki/transmission-chain.md` for the spine.', '>',
           '> Auto-generated by `tools/timeline_header.py --chain`. Do not hand-edit.', '', '## Stages', '']
    for num, name, got in present:
        out.append(f'- **{num}. {name}** — ' + (', '.join(f'`{g}`' for g in got) or '_(no note yet)_'))
    out.append('')
    cur = None
    for d, num, name, fn, i, txt in rows:
        if d[:7] != cur:
            cur = d[:7]
            out += ['', f'## {cur}', '']
        out.append(f'- `{d}` **[{num}]** {fn}:L{i} — {txt[:150]}')
    open(os.path.join(TLDIR, '_chain.md'), 'w').write('\n'.join(out) + '\n')
    return len(rows)

def main():
    a = sys.argv[1:]
    if '--chain' in a:
        n = build_chain()
        print(f'  chain log: {n} entries -> wiki/_timelines/_chain.md')
        if '--threads' not in a:
            return
    if '--threads' in a:
        print(f'  built {build_threads()} thread timelines in wiki/_timelines/')
        return
    if '--note' in a:
        p = os.path.join(ROOT, a[a.index('--note') + 1])
        ch, n = apply(p)
        print(f'  {"updated" if ch else "unchanged"}  {os.path.relpath(p, ROOT)}  ({n} entries)')
        return
    check = '--check' in a
    tot = ch_n = 0
    for p in notes():
        ch, n = apply(p, write=not check)
        tot += 1
        if ch:
            ch_n += 1
            print(f'  {"STALE" if check else "updated"}  {os.path.relpath(p, ROOT):<44} {n:>4} entries')
    print(f'  {ch_n}/{tot} notes {"stale" if check else "refreshed"}')


if __name__ == '__main__':
    main()
